const careerBase = [
  [
    "baakanya-auto",
    "Baakanya Auto",
    "minimal",
    "#17252d",
    "#58bcec",
    "none",
    "We choose the cleanest layout for your information.",
  ],
  [
    "executive",
    "Executive",
    "classic",
    "#16222a",
    "#a98b52",
    "none",
    "A restrained leadership layout with strong hierarchy.",
  ],
  [
    "modern-ats",
    "Modern ATS",
    "minimal",
    "#18313d",
    "#3d9acb",
    "none",
    "Single-column and optimised for applicant tracking systems.",
  ],
  [
    "professional-blue",
    "Professional Blue",
    "band",
    "#12344b",
    "#59b9e8",
    "square",
    "Confident structure with an optional square portrait.",
  ],
  [
    "consultant",
    "Consultant",
    "sidebar",
    "#24343c",
    "#9ccadf",
    "circle",
    "Compact facts and a polished circular portrait.",
  ],
  [
    "finance",
    "Finance",
    "classic",
    "#17332b",
    "#6ca88e",
    "none",
    "Conservative typography for finance and operations.",
  ],
  [
    "legal",
    "Legal",
    "classic",
    "#25272b",
    "#8f7961",
    "none",
    "Traditional, composed and highly readable.",
  ],
  [
    "technology",
    "Technology",
    "sidebar",
    "#172936",
    "#55bce9",
    "square",
    "Structured for technical skills and project evidence.",
  ],
  [
    "healthcare",
    "Healthcare",
    "minimal",
    "#17433e",
    "#66b8a6",
    "circle",
    "Calm and precise for health and care professionals.",
  ],
  [
    "education",
    "Education",
    "band",
    "#34305f",
    "#9c8ee6",
    "circle",
    "Warm authority for teaching and academic roles.",
  ],
  [
    "creative",
    "Creative Professional",
    "sidebar",
    "#392a3d",
    "#d88bb7",
    "square",
    "Expressive without sacrificing professional clarity.",
  ],
  [
    "engineering",
    "Engineering",
    "band",
    "#27333a",
    "#e0a44e",
    "none",
    "Technical hierarchy for projects and qualifications.",
  ],
  [
    "graduate",
    "Graduate",
    "minimal",
    "#263a4a",
    "#6eb7df",
    "circle",
    "Balances education, projects and transferable skills.",
  ],
  [
    "hospitality",
    "Hospitality",
    "sidebar",
    "#3a2f25",
    "#d7a76f",
    "circle",
    "Welcoming and service-focused with a refined portrait.",
  ],
  [
    "public-service",
    "Public Service",
    "classic",
    "#20374a",
    "#7ba4c4",
    "none",
    "Formal, accessible and suited to institutional roles.",
  ],
  [
    "sales",
    "Sales",
    "band",
    "#243849",
    "#5eb6df",
    "square",
    "Achievement-led layout for commercial professionals.",
  ],
  [
    "compact",
    "Compact",
    "minimal",
    "#222f35",
    "#79949f",
    "none",
    "Fits substantial experience into a disciplined layout.",
  ],
  [
    "monochrome",
    "Monochrome",
    "classic",
    "#16191b",
    "#777777",
    "none",
    "Print-safe black and white presentation.",
  ],
  [
    "botswana",
    "Botswana Professional",
    "band",
    "#17252d",
    "#65b8e7",
    "circle",
    "Modern local professional style with restrained colour.",
  ],
  [
    "portfolio",
    "Portfolio Lead",
    "sidebar",
    "#202a3d",
    "#8aa9ff",
    "square",
    "A confident profile-led option for senior specialists.",
  ],
];

const businessBase = [
  [
    "baakanya-auto",
    "Baakanya Auto",
    "clean",
    "#17252d",
    "#58bcec",
    "We format the information into the clearest invoice.",
  ],
  [
    "corporate",
    "Corporate",
    "band",
    "#142b3a",
    "#66b5e5",
    "Boardroom-ready invoice with clear payment details.",
  ],
  [
    "executive",
    "Executive",
    "formal",
    "#20262a",
    "#a98b52",
    "Refined invoice typography for established firms.",
  ],
  [
    "minimal",
    "Minimal",
    "clean",
    "#262f34",
    "#93a7b0",
    "Simple, spacious invoice that is easy to scan.",
  ],
  [
    "blueprint",
    "Blueprint",
    "band",
    "#123b59",
    "#55bce9",
    "Technical invoice layout for project billing.",
  ],
  [
    "accounting",
    "Accounting",
    "formal",
    "#18372e",
    "#61a789",
    "Conservative invoice for financial services.",
  ],
  [
    "consulting",
    "Consulting",
    "side",
    "#2d3440",
    "#769dd3",
    "Strong brand rail and organised invoice totals.",
  ],
  [
    "creative",
    "Creative Studio",
    "side",
    "#3c2941",
    "#d78ab5",
    "Distinctive invoice that stays client-appropriate.",
  ],
  [
    "construction",
    "Construction",
    "band",
    "#293238",
    "#e0a348",
    "Robust invoice structure for services and materials.",
  ],
  [
    "legal",
    "Legal",
    "formal",
    "#242628",
    "#8d775f",
    "Traditional invoice styling for professional practices.",
  ],
  [
    "medical",
    "Medical",
    "clean",
    "#17423e",
    "#67b9a7",
    "Calm, clear invoice for healthcare billing.",
  ],
  [
    "retail",
    "Retail",
    "band",
    "#253a48",
    "#64b9df",
    "Friendly invoice for products and services.",
  ],
  [
    "hospitality",
    "Hospitality",
    "side",
    "#3b3027",
    "#d1a36d",
    "Warm premium invoice for guest services.",
  ],
  [
    "technology",
    "Technology",
    "side",
    "#182b38",
    "#54bceb",
    "Modern modular invoice for digital work.",
  ],
  [
    "monochrome",
    "Monochrome",
    "formal",
    "#17191a",
    "#767676",
    "Ink-efficient invoice for reliable printing.",
  ],
  [
    "compact",
    "Compact",
    "clean",
    "#24343b",
    "#7896a2",
    "More invoice line items without visual clutter.",
  ],
  [
    "premium",
    "Premium",
    "formal",
    "#202737",
    "#b39a5c",
    "Elegant invoice detail for premium client work.",
  ],
  [
    "freelancer",
    "Freelancer",
    "band",
    "#26364b",
    "#6eaee1",
    "Approachable invoice for independent work.",
  ],
  [
    "botswana",
    "Botswana Business",
    "band",
    "#17252d",
    "#65b8e7",
    "Clean local-business invoice presentation.",
  ],
  [
    "statement",
    "Statement",
    "side",
    "#25323a",
    "#87a6b5",
    "Systematic invoice built for record keeping.",
  ],
];

/** Quotation templates use different layouts/colours so they do not mirror invoices. */
const quotationBase = [
  [
    "baakanya-auto",
    "Baakanya Auto",
    "proposal",
    "#1a3a2e",
    "#3db88a",
    "We format your quote into a clear proposal document.",
  ],
  [
    "proposal",
    "Proposal",
    "proposal",
    "#1e3d52",
    "#4aa3d4",
    "Client proposal layout with validity front and centre.",
  ],
  [
    "estimate",
    "Estimate",
    "estimate",
    "#3a2f1f",
    "#c9a227",
    "Estimate-style quote with soft gold accents.",
  ],
  [
    "tender",
    "Tender",
    "formal",
    "#2a3038",
    "#7a8fa3",
    "Formal tender presentation for structured bids.",
  ],
  [
    "scope",
    "Scope of Work",
    "scope",
    "#243b55",
    "#5b9fd4",
    "Scope-led quotation with clear deliverable rows.",
  ],
  [
    "project",
    "Project Quote",
    "band",
    "#0f3d4a",
    "#2ec4b6",
    "Project quotation with a teal authority band.",
  ],
  [
    "studio",
    "Studio Quote",
    "side",
    "#4a2342",
    "#e091c4",
    "Creative studio quotation with a brand rail.",
  ],
  [
    "contractor",
    "Contractor",
    "estimate",
    "#2f3630",
    "#d4a017",
    "Practical quote for trades and contractor work.",
  ],
  [
    "agency",
    "Agency",
    "proposal",
    "#1c2740",
    "#6c8cff",
    "Agency-ready proposal quote with cool blue tones.",
  ],
  [
    "services",
    "Services",
    "clean",
    "#234038",
    "#4caf8f",
    "Service quotation with calm green hierarchy.",
  ],
  [
    "supply",
    "Supply Quote",
    "scope",
    "#2c333a",
    "#8aa4b5",
    "Supply and materials quotation with dense rows.",
  ],
  [
    "event",
    "Event Quote",
    "band",
    "#3d2748",
    "#c084fc",
    "Event quotation with a bold header presentation.",
  ],
  [
    "hospitality",
    "Hospitality Quote",
    "proposal",
    "#3b2a1e",
    "#d4a574",
    "Warm hospitality quotation for guest packages.",
  ],
  [
    "tech",
    "Tech Quote",
    "side",
    "#132a38",
    "#38bdf8",
    "Modern tech quotation with a side accent rail.",
  ],
  [
    "mono",
    "Mono Quote",
    "formal",
    "#1a1c1e",
    "#6b7280",
    "Print-safe monochrome quotation.",
  ],
  [
    "brief",
    "Brief Quote",
    "clean",
    "#1f3340",
    "#6495a8",
    "Compact quotation for short scopes of work.",
  ],
  [
    "premium",
    "Premium Quote",
    "proposal",
    "#1f2433",
    "#c9a45c",
    "Premium proposal quotation with gold accents.",
  ],
  [
    "freelance",
    "Freelance Quote",
    "estimate",
    "#243447",
    "#7eb6e0",
    "Friendly quote for independent professionals.",
  ],
  [
    "botswana",
    "Botswana Quote",
    "band",
    "#163028",
    "#3ecf9a",
    "Local-business quotation with green accents.",
  ],
  [
    "detailed",
    "Detailed Quote",
    "scope",
    "#25323a",
    "#6f93a8",
    "Detailed quotation built for itemised proposals.",
  ],
];

const mapTemplates = (items, type) =>
  items.map(
    ([id, name, layout, primary, accent, photoOrDescription, description]) => ({
      id: `${type}-${id}`,
      name,
      layout,
      primary,
      accent,
      photo: description ? photoOrDescription : "none",
      description: description || photoOrDescription,
      recommended: ["baakanya-auto", "modern-ats", "corporate", "proposal"].includes(
        id,
      ),
      type,
    }),
  );

export const cvTemplates = mapTemplates(careerBase, "cv");
export const coverLetterTemplates = mapTemplates(careerBase, "cover");
export const invoiceTemplates = mapTemplates(businessBase, "invoice");
export const quotationTemplates = mapTemplates(quotationBase, "quotation");
