import { defaultSectionTitles } from "./customization";

const cv = (
  id,
  name,
  layout,
  primary,
  accent,
  photo,
  description,
  extras = {},
) => ({
  id: `cv-${id}`,
  name,
  layout,
  primary,
  accent,
  photo,
  description,
  type: "cv",
  background: extras.background || "#ffffff",
  font: extras.font || "calibri",
  density: extras.density || "comfortable",
  lineSpacing: extras.lineSpacing || "1.15",
  headingStyle: extras.headingStyle || "underline",
  ruleStyle: extras.ruleStyle || "accent",
  titles: { ...defaultSectionTitles, ...(extras.titles || {}) },
  recommended: Boolean(extras.recommended),
});

const cover = (
  id,
  name,
  layout,
  primary,
  accent,
  photo,
  description,
  extras = {},
) => ({
  id: `cover-${id}`,
  name,
  layout,
  primary,
  accent,
  photo,
  description,
  type: "cover",
  background: extras.background || "#ffffff",
  font: extras.font || "georgia",
  density: extras.density || "comfortable",
  lineSpacing: extras.lineSpacing || "1.5",
  headingStyle: extras.headingStyle || "underline",
  ruleStyle: extras.ruleStyle || "accent",
  recommended: Boolean(extras.recommended),
});

const invoice = (
  id,
  name,
  layout,
  primary,
  accent,
  description,
  extras = {},
) => ({
  id: `invoice-${id}`,
  name,
  layout,
  primary,
  accent,
  photo: "none",
  description,
  type: "invoice",
  background: extras.background || "#ffffff",
  font: extras.font || "arial",
  density: extras.density || "comfortable",
  lineSpacing: extras.lineSpacing || "1.15",
  headingStyle: extras.headingStyle || "plain",
  ruleStyle: extras.ruleStyle || "accent",
  recommended: Boolean(extras.recommended),
});

const quotation = (
  id,
  name,
  layout,
  primary,
  accent,
  description,
  extras = {},
) => ({
  id: `quotation-${id}`,
  name,
  layout,
  primary,
  accent,
  photo: "none",
  description,
  type: "quotation",
  background: extras.background || "#ffffff",
  font: extras.font || "calibri",
  density: extras.density || "comfortable",
  lineSpacing: extras.lineSpacing || "1.15",
  headingStyle: extras.headingStyle || "plain",
  ruleStyle: extras.ruleStyle || "accent",
  recommended: Boolean(extras.recommended),
});

/** Each CV template uses a unique layout + type treatment. */
export const cvTemplates = [
  cv(
    "baakanya-auto",
    "Baakanya Auto",
    "minimal",
    "#17252d",
    "#58bcec",
    "none",
    "Clean single-column layout chosen for clarity.",
    {
      recommended: true,
      font: "calibri",
      headingStyle: "underline",
      ruleStyle: "accent",
    },
  ),
  cv(
    "executive",
    "Executive",
    "centered",
    "#16222a",
    "#a98b52",
    "none",
    "Centered leadership letterhead with gold hierarchy.",
    {
      font: "garamond",
      density: "spacious",
      lineSpacing: "1.5",
      headingStyle: "plain",
      ruleStyle: "double",
      titles: {
        profile: "Executive summary",
        experience: "Leadership experience",
        skills: "Capabilities",
      },
    },
  ),
  cv(
    "modern-ats",
    "Modern ATS",
    "classic",
    "#18313d",
    "#3d9acb",
    "none",
    "ATS-safe single column with plain section labels.",
    {
      recommended: true,
      font: "arial",
      headingStyle: "plain",
      ruleStyle: "hairline",
      titles: {
        profile: "Summary",
        experience: "Work experience",
        skills: "Skills",
      },
    },
  ),
  cv(
    "professional-blue",
    "Professional Blue",
    "band",
    "#12344b",
    "#59b9e8",
    "square",
    "Bold blue header band with square portrait.",
    {
      font: "segoe-ui",
      headingStyle: "leftbar",
      ruleStyle: "accent",
    },
  ),
  cv(
    "consultant",
    "Consultant",
    "sidebar",
    "#24343c",
    "#9ccadf",
    "circle",
    "Two-column consultant layout with circular portrait.",
    {
      font: "calibri",
      density: "compact",
      headingStyle: "pill",
      titles: {
        profile: "About",
        experience: "Engagements",
        skills: "Expertise",
      },
    },
  ),
  cv(
    "finance",
    "Finance",
    "split",
    "#17332b",
    "#6ca88e",
    "none",
    "Split header with conservative finance green accents.",
    {
      font: "times-new-roman",
      headingStyle: "boxed",
      ruleStyle: "double",
      titles: {
        profile: "Profile",
        experience: "Professional experience",
        certifications: "Professional memberships",
      },
    },
  ),
  cv(
    "legal",
    "Legal",
    "stacked",
    "#25272b",
    "#8f7961",
    "none",
    "Traditional stacked name block for legal roles.",
    {
      font: "garamond",
      lineSpacing: "1.5",
      headingStyle: "plain",
      ruleStyle: "double",
      titles: {
        profile: "Professional overview",
        experience: "Practice experience",
        education: "Academic background",
      },
    },
  ),
  cv(
    "technology",
    "Technology",
    "sidebar",
    "#0f2740",
    "#38bdf8",
    "square",
    "Tech sidebar with project-led section wording.",
    {
      font: "consolas",
      density: "compact",
      background: "#f7fafc",
      headingStyle: "leftbar",
      titles: {
        profile: "Summary",
        experience: "Projects & experience",
        skills: "Technical skills",
      },
    },
  ),
  cv(
    "healthcare",
    "Healthcare",
    "flag",
    "#17433e",
    "#66b8a6",
    "circle",
    "Calm flag-accent sections for care professionals.",
    {
      font: "candara",
      headingStyle: "leftbar",
      titles: {
        profile: "Professional statement",
        experience: "Clinical experience",
        certifications: "Registrations & certificates",
      },
    },
  ),
  cv(
    "education",
    "Education",
    "band",
    "#34305f",
    "#9c8ee6",
    "circle",
    "Warm violet band for teaching and academic CVs.",
    {
      font: "georgia",
      headingStyle: "pill",
      titles: {
        profile: "Teaching philosophy",
        experience: "Teaching experience",
        education: "Qualifications",
      },
    },
  ),
  cv(
    "creative",
    "Creative Professional",
    "panel",
    "#392a3d",
    "#d88bb7",
    "square",
    "Tinted panel header for creative specialists.",
    {
      font: "century-gothic",
      background: "#fcf8fb",
      headingStyle: "pill",
      titles: {
        profile: "Creative focus",
        experience: "Selected work",
        skills: "Tools & craft",
      },
    },
  ),
  cv(
    "engineering",
    "Engineering",
    "split",
    "#27333a",
    "#e0a44e",
    "none",
    "Technical split header with amber accents.",
    {
      font: "arial-narrow",
      density: "compact",
      headingStyle: "boxed",
      titles: {
        profile: "Technical profile",
        experience: "Project experience",
        skills: "Engineering skills",
      },
    },
  ),
  cv(
    "graduate",
    "Graduate",
    "modern",
    "#263a4a",
    "#6eb7df",
    "circle",
    "Modern graduate layout emphasising education first.",
    {
      font: "segoe-ui",
      headingStyle: "plain",
      titles: {
        profile: "About me",
        experience: "Experience & projects",
        education: "Education",
        skills: "Skills & strengths",
      },
    },
  ),
  cv(
    "hospitality",
    "Hospitality",
    "sidebar",
    "#3a2f25",
    "#d7a76f",
    "circle",
    "Warm hospitality sidebar with service-focused titles.",
    {
      font: "georgia",
      headingStyle: "underline",
      titles: {
        profile: "Service profile",
        experience: "Hospitality experience",
        skills: "Guest service skills",
      },
    },
  ),
  cv(
    "public-service",
    "Public Service",
    "classic",
    "#20374a",
    "#7ba4c4",
    "none",
    "Institutional classic layout for public-sector roles.",
    {
      font: "times-new-roman",
      headingStyle: "boxed",
      ruleStyle: "hairline",
      titles: {
        profile: "Career summary",
        experience: "Employment history",
        skills: "Competencies",
      },
    },
  ),
  cv(
    "sales",
    "Sales",
    "band",
    "#1a3344",
    "#2dd4bf",
    "square",
    "Achievement-led band layout for commercial roles.",
    {
      font: "franklin-gothic",
      headingStyle: "leftbar",
      titles: {
        profile: "Value proposition",
        experience: "Sales achievements",
        skills: "Commercial skills",
      },
    },
  ),
  cv(
    "compact",
    "Compact",
    "flag",
    "#222f35",
    "#79949f",
    "none",
    "Dense flag layout for substantial experience on one page.",
    {
      font: "arial-narrow",
      density: "compact",
      lineSpacing: "1",
      headingStyle: "plain",
      ruleStyle: "hairline",
    },
  ),
  cv(
    "monochrome",
    "Monochrome",
    "stacked",
    "#16191b",
    "#555555",
    "none",
    "Print-safe black and white stacked presentation.",
    {
      font: "arial",
      headingStyle: "plain",
      ruleStyle: "double",
      background: "#ffffff",
    },
  ),
  cv(
    "botswana",
    "Botswana Professional",
    "modern",
    "#0c3b5a",
    "#65b8e7",
    "circle",
    "Local professional modern layout with sky-blue accents.",
    {
      font: "calibri",
      headingStyle: "pill",
      titles: {
        profile: "Professional profile",
        experience: "Work history",
      },
    },
  ),
  cv(
    "portfolio",
    "Portfolio Lead",
    "panel",
    "#1a2744",
    "#8aa9ff",
    "square",
    "Indigo panel header for senior specialists.",
    {
      font: "corbel",
      background: "#f5f7fc",
      headingStyle: "boxed",
      titles: {
        profile: "Practice overview",
        experience: "Selected engagements",
        skills: "Specialisms",
      },
    },
  ),
];

/** Cover letter templates — unique from CV layouts. */
export const coverLetterTemplates = [
  cover(
    "baakanya-auto",
    "Baakanya Auto",
    "letter",
    "#17252d",
    "#58bcec",
    "none",
    "Clear professional letter layout.",
    { recommended: true, font: "georgia", headingStyle: "underline" },
  ),
  cover(
    "executive",
    "Executive",
    "executive",
    "#16222a",
    "#a98b52",
    "none",
    "Right-weighted executive letterhead with gold rule.",
    { font: "garamond", lineSpacing: "1.5", ruleStyle: "double" },
  ),
  cover(
    "modern-ats",
    "Modern ATS",
    "letter",
    "#18313d",
    "#3d9acb",
    "none",
    "Plain ATS-friendly letter with simple hierarchy.",
    { font: "arial", ruleStyle: "hairline", headingStyle: "plain" },
  ),
  cover(
    "professional-blue",
    "Professional Blue",
    "band",
    "#12344b",
    "#59b9e8",
    "square",
    "Blue letterhead band with square portrait option.",
    { font: "calibri" },
  ),
  cover(
    "consultant",
    "Consultant",
    "rail",
    "#24343c",
    "#9ccadf",
    "circle",
    "Left rail accent for consulting applications.",
    { font: "calibri", density: "compact" },
  ),
  cover(
    "finance",
    "Finance",
    "framed",
    "#17332b",
    "#6ca88e",
    "none",
    "Framed formal letter for finance applications.",
    { font: "times-new-roman", ruleStyle: "double" },
  ),
  cover(
    "legal",
    "Legal",
    "classic-block",
    "#25272b",
    "#8f7961",
    "none",
    "Traditional legal letter with formal recipient block.",
    { font: "garamond", lineSpacing: "1.5", ruleStyle: "double" },
  ),
  cover(
    "technology",
    "Technology",
    "accent-top",
    "#0f2740",
    "#38bdf8",
    "square",
    "Thick top accent bar for technology roles.",
    { font: "segoe-ui", background: "#f8fbfd" },
  ),
  cover(
    "healthcare",
    "Healthcare",
    "letter",
    "#17433e",
    "#66b8a6",
    "circle",
    "Calm healthcare letter with soft teal accents.",
    { font: "candara", headingStyle: "leftbar" },
  ),
  cover(
    "education",
    "Education",
    "band",
    "#34305f",
    "#9c8ee6",
    "circle",
    "Academic band letterhead in violet tones.",
    { font: "georgia" },
  ),
  cover(
    "creative",
    "Creative Professional",
    "modern-block",
    "#392a3d",
    "#d88bb7",
    "square",
    "Modern subject block for creative applications.",
    { font: "century-gothic", background: "#fcf8fb" },
  ),
  cover(
    "engineering",
    "Engineering",
    "rail",
    "#27333a",
    "#e0a44e",
    "none",
    "Engineering rail letter with amber accent.",
    { font: "arial-narrow", density: "compact" },
  ),
  cover(
    "graduate",
    "Graduate",
    "centered",
    "#263a4a",
    "#6eb7df",
    "circle",
    "Centered graduate letterhead, friendly and clear.",
    { font: "segoe-ui", lineSpacing: "1.5" },
  ),
  cover(
    "hospitality",
    "Hospitality",
    "signature",
    "#3a2f25",
    "#d7a76f",
    "circle",
    "Warm hospitality letter with signature emphasis.",
    { font: "georgia", lineSpacing: "1.5" },
  ),
  cover(
    "public-service",
    "Public Service",
    "classic-block",
    "#20374a",
    "#7ba4c4",
    "none",
    "Institutional classic-block letter format.",
    { font: "times-new-roman", ruleStyle: "hairline" },
  ),
  cover(
    "sales",
    "Sales",
    "accent-top",
    "#1a3344",
    "#2dd4bf",
    "square",
    "Confident sales letter with teal top accent.",
    { font: "franklin-gothic" },
  ),
  cover(
    "compact",
    "Compact",
    "letter",
    "#222f35",
    "#79949f",
    "none",
    "Compact letter spacing for longer applications.",
    { font: "arial-narrow", density: "compact", lineSpacing: "1.15" },
  ),
  cover(
    "monochrome",
    "Monochrome",
    "framed",
    "#16191b",
    "#555555",
    "none",
    "Print-safe monochrome framed letter.",
    { font: "arial", ruleStyle: "double" },
  ),
  cover(
    "botswana",
    "Botswana Professional",
    "band",
    "#0c3b5a",
    "#65b8e7",
    "circle",
    "Local professional band letter with sky accents.",
    { font: "calibri" },
  ),
  cover(
    "portfolio",
    "Portfolio Lead",
    "executive",
    "#1a2744",
    "#8aa9ff",
    "square",
    "Senior portfolio letter with indigo emphasis.",
    { font: "corbel", background: "#f5f7fc", ruleStyle: "accent" },
  ),
];

export const invoiceTemplates = [
  invoice(
    "baakanya-auto",
    "Baakanya Auto",
    "clean",
    "#17252d",
    "#58bcec",
    "Clear invoice layout for everyday billing.",
    { recommended: true, font: "arial" },
  ),
  invoice(
    "corporate",
    "Corporate",
    "band",
    "#142b3a",
    "#66b5e5",
    "Boardroom invoice with a solid corporate header band.",
    { recommended: true, font: "segoe-ui" },
  ),
  invoice(
    "executive",
    "Executive",
    "masthead",
    "#20262a",
    "#a98b52",
    "Gold masthead invoice for established firms.",
    { font: "garamond", density: "spacious" },
  ),
  invoice(
    "minimal",
    "Minimal",
    "clean",
    "#4a5560",
    "#a0aec0",
    "Spacious minimal invoice with soft grey accents.",
    { font: "helvetica", density: "spacious", background: "#fbfcfd" },
  ),
  invoice(
    "blueprint",
    "Blueprint",
    "stripe",
    "#123b59",
    "#55bce9",
    "Technical striped invoice for project billing.",
    { font: "consolas", density: "compact" },
  ),
  invoice(
    "accounting",
    "Accounting",
    "ledger",
    "#18372e",
    "#61a789",
    "Ledger-style rows for financial services.",
    { font: "times-new-roman", headingStyle: "boxed" },
  ),
  invoice(
    "consulting",
    "Consulting",
    "side",
    "#2d3440",
    "#769dd3",
    "Brand rail invoice for consulting retainers.",
    { font: "calibri" },
  ),
  invoice(
    "creative",
    "Creative Studio",
    "corner",
    "#3c2941",
    "#d78ab5",
    "Corner-accent invoice for creative studios.",
    { font: "century-gothic", background: "#fdf8fb" },
  ),
  invoice(
    "construction",
    "Construction",
    "band",
    "#293238",
    "#e0a348",
    "Robust amber-band invoice for trades.",
    { font: "arial-narrow", density: "compact" },
  ),
  invoice(
    "legal",
    "Legal",
    "formal",
    "#242628",
    "#8d775f",
    "Traditional formal invoice for practices.",
    { font: "garamond", ruleStyle: "double" },
  ),
  invoice(
    "medical",
    "Medical",
    "boxed",
    "#17423e",
    "#67b9a7",
    "Boxed totals card for healthcare billing.",
    { font: "candara" },
  ),
  invoice(
    "retail",
    "Retail",
    "stripe",
    "#253a48",
    "#64b9df",
    "Friendly striped invoice for retail sales.",
    { font: "segoe-ui" },
  ),
  invoice(
    "hospitality",
    "Hospitality",
    "masthead",
    "#3b3027",
    "#d1a36d",
    "Warm masthead invoice for guest services.",
    { font: "georgia" },
  ),
  invoice(
    "technology",
    "Technology",
    "side",
    "#182b38",
    "#54bceb",
    "Modern side-rail invoice for digital work.",
    { font: "consolas", background: "#f7fafc" },
  ),
  invoice(
    "monochrome",
    "Monochrome",
    "formal",
    "#17191a",
    "#767676",
    "Ink-efficient monochrome formal invoice.",
    { font: "arial", ruleStyle: "hairline" },
  ),
  invoice(
    "compact",
    "Compact",
    "ledger",
    "#24343b",
    "#7896a2",
    "Dense ledger invoice for many line items.",
    { font: "arial-narrow", density: "compact", lineSpacing: "1" },
  ),
  invoice(
    "premium",
    "Premium",
    "corner",
    "#202737",
    "#b39a5c",
    "Premium gold-corner invoice for high-value work.",
    { font: "garamond", density: "spacious" },
  ),
  invoice(
    "freelancer",
    "Freelancer",
    "split-bill",
    "#26364b",
    "#6eaee1",
    "Split bill-to / totals layout for freelancers.",
    { font: "calibri" },
  ),
  invoice(
    "botswana",
    "Botswana Business",
    "band",
    "#0c3b5a",
    "#65b8e7",
    "Local-business band invoice with sky accents.",
    { font: "calibri" },
  ),
  invoice(
    "statement",
    "Statement",
    "ledger",
    "#25323a",
    "#87a6b5",
    "Statement-style ledger for record keeping.",
    { font: "times-new-roman", density: "compact" },
  ),
];

export const quotationTemplates = [
  quotation(
    "baakanya-auto",
    "Baakanya Auto",
    "proposal",
    "#1a3a2e",
    "#3db88a",
    "Clear proposal quotation with green authority.",
    { recommended: true, font: "calibri" },
  ),
  quotation(
    "proposal",
    "Proposal",
    "proposal",
    "#1e3d52",
    "#4aa3d4",
    "Client proposal with validity highlighted.",
    { recommended: true, font: "segoe-ui" },
  ),
  quotation(
    "estimate",
    "Estimate",
    "estimate",
    "#3a2f1f",
    "#c9a227",
    "Gold estimate banner for provisional pricing.",
    { font: "georgia" },
  ),
  quotation(
    "tender",
    "Tender",
    "formal",
    "#2a3038",
    "#7a8fa3",
    "Formal tender quotation for structured bids.",
    { font: "times-new-roman", ruleStyle: "double" },
  ),
  quotation(
    "scope",
    "Scope of Work",
    "scope",
    "#243b55",
    "#5b9fd4",
    "Scope-led deliverable quotation.",
    { font: "arial", density: "compact" },
  ),
  quotation(
    "project",
    "Project Quote",
    "band",
    "#0f3d4a",
    "#2ec4b6",
    "Teal project band quotation.",
    { font: "segoe-ui" },
  ),
  quotation(
    "studio",
    "Studio Quote",
    "side",
    "#4a2342",
    "#e091c4",
    "Creative studio rail quotation.",
    { font: "century-gothic", background: "#fdf8fb" },
  ),
  quotation(
    "contractor",
    "Contractor",
    "estimate",
    "#2f3630",
    "#d4a017",
    "Practical contractor estimate quote.",
    { font: "arial-narrow", density: "compact" },
  ),
  quotation(
    "agency",
    "Agency",
    "masthead",
    "#1c2740",
    "#6c8cff",
    "Agency masthead proposal quotation.",
    { font: "corbel" },
  ),
  quotation(
    "services",
    "Services",
    "clean",
    "#234038",
    "#4caf8f",
    "Calm green services quotation.",
    { font: "candara", density: "spacious" },
  ),
  quotation(
    "supply",
    "Supply Quote",
    "ledger",
    "#2c333a",
    "#8aa4b5",
    "Supply ledger for materials quotations.",
    { font: "consolas", density: "compact" },
  ),
  quotation(
    "event",
    "Event Quote",
    "corner",
    "#3d2748",
    "#c084fc",
    "Event quotation with violet corner accent.",
    { font: "segoe-ui", background: "#faf7fc" },
  ),
  quotation(
    "hospitality",
    "Hospitality Quote",
    "proposal",
    "#3b2a1e",
    "#d4a574",
    "Warm hospitality package quotation.",
    { font: "georgia" },
  ),
  quotation(
    "tech",
    "Tech Quote",
    "side",
    "#132a38",
    "#38bdf8",
    "Modern tech rail quotation.",
    { font: "consolas", background: "#f7fafc" },
  ),
  quotation(
    "mono",
    "Mono Quote",
    "formal",
    "#1a1c1e",
    "#6b7280",
    "Print-safe monochrome quotation.",
    { font: "arial", ruleStyle: "hairline" },
  ),
  quotation(
    "brief",
    "Brief Quote",
    "boxed",
    "#1f3340",
    "#6495a8",
    "Compact boxed quotation for short scopes.",
    { font: "arial-narrow", density: "compact" },
  ),
  quotation(
    "premium",
    "Premium Quote",
    "masthead",
    "#1f2433",
    "#c9a45c",
    "Premium gold masthead quotation.",
    { font: "garamond", density: "spacious" },
  ),
  quotation(
    "freelance",
    "Freelance Quote",
    "split-bill",
    "#243447",
    "#7eb6e0",
    "Split freelance quotation layout.",
    { font: "calibri" },
  ),
  quotation(
    "botswana",
    "Botswana Quote",
    "band",
    "#163028",
    "#3ecf9a",
    "Local-business green band quotation.",
    { font: "calibri" },
  ),
  quotation(
    "detailed",
    "Detailed Quote",
    "scope",
    "#25323a",
    "#6f93a8",
    "Detailed scope quotation for itemised proposals.",
    { font: "times-new-roman", density: "compact" },
  ),
];
