const careerBase = [
  [
    "baakanya-auto",
    "Baakanya Auto",
    "minimal",
    "#17252d",
    "#58bcec",
    "none",
    "We choose the cleanest layout for your information.",
  ],
  [
    "executive",
    "Executive",
    "classic",
    "#16222a",
    "#a98b52",
    "none",
    "A restrained leadership layout with strong hierarchy.",
  ],
  [
    "modern-ats",
    "Modern ATS",
    "minimal",
    "#18313d",
    "#3d9acb",
    "none",
    "Single-column and optimised for applicant tracking systems.",
  ],
  [
    "professional-blue",
    "Professional Blue",
    "band",
    "#12344b",
    "#59b9e8",
    "square",
    "Confident structure with an optional square portrait.",
  ],
  [
    "consultant",
    "Consultant",
    "sidebar",
    "#24343c",
    "#9ccadf",
    "circle",
    "Compact facts and a polished circular portrait.",
  ],
  [
    "finance",
    "Finance",
    "classic",
    "#17332b",
    "#6ca88e",
    "none",
    "Conservative typography for finance and operations.",
  ],
  [
    "legal",
    "Legal",
    "classic",
    "#25272b",
    "#8f7961",
    "none",
    "Traditional, composed and highly readable.",
  ],
  [
    "technology",
    "Technology",
    "sidebar",
    "#172936",
    "#55bce9",
    "square",
    "Structured for technical skills and project evidence.",
  ],
  [
    "healthcare",
    "Healthcare",
    "minimal",
    "#17433e",
    "#66b8a6",
    "circle",
    "Calm and precise for health and care professionals.",
  ],
  [
    "education",
    "Education",
    "band",
    "#34305f",
    "#9c8ee6",
    "circle",
    "Warm authority for teaching and academic roles.",
  ],
  [
    "creative",
    "Creative Professional",
    "sidebar",
    "#392a3d",
    "#d88bb7",
    "square",
    "Expressive without sacrificing professional clarity.",
  ],
  [
    "engineering",
    "Engineering",
    "band",
    "#27333a",
    "#e0a44e",
    "none",
    "Technical hierarchy for projects and qualifications.",
  ],
  [
    "graduate",
    "Graduate",
    "minimal",
    "#263a4a",
    "#6eb7df",
    "circle",
    "Balances education, projects and transferable skills.",
  ],
  [
    "hospitality",
    "Hospitality",
    "sidebar",
    "#3a2f25",
    "#d7a76f",
    "circle",
    "Welcoming and service-focused with a refined portrait.",
  ],
  [
    "public-service",
    "Public Service",
    "classic",
    "#20374a",
    "#7ba4c4",
    "none",
    "Formal, accessible and suited to institutional roles.",
  ],
  [
    "sales",
    "Sales",
    "band",
    "#243849",
    "#5eb6df",
    "square",
    "Achievement-led layout for commercial professionals.",
  ],
  [
    "compact",
    "Compact",
    "minimal",
    "#222f35",
    "#79949f",
    "none",
    "Fits substantial experience into a disciplined layout.",
  ],
  [
    "monochrome",
    "Monochrome",
    "classic",
    "#16191b",
    "#777777",
    "none",
    "Print-safe black and white presentation.",
  ],
  [
    "botswana",
    "Botswana Professional",
    "band",
    "#17252d",
    "#65b8e7",
    "circle",
    "Modern local professional style with restrained colour.",
  ],
  [
    "portfolio",
    "Portfolio Lead",
    "sidebar",
    "#202a3d",
    "#8aa9ff",
    "square",
    "A confident profile-led option for senior specialists.",
  ],
];

const businessBase = [
  [
    "baakanya-auto",
    "Baakanya Auto",
    "clean",
    "#17252d",
    "#58bcec",
    "We format the information into the clearest document.",
  ],
  [
    "corporate",
    "Corporate",
    "band",
    "#142b3a",
    "#66b5e5",
    "Boardroom-ready with clear payment details.",
  ],
  [
    "executive",
    "Executive",
    "formal",
    "#20262a",
    "#a98b52",
    "Refined typography for established firms.",
  ],
  [
    "minimal",
    "Minimal",
    "clean",
    "#262f34",
    "#93a7b0",
    "Simple, spacious and easy to scan.",
  ],
  [
    "blueprint",
    "Blueprint",
    "band",
    "#123b59",
    "#55bce9",
    "Technical and precise for project work.",
  ],
  [
    "accounting",
    "Accounting",
    "formal",
    "#18372e",
    "#61a789",
    "Conservative layout for financial services.",
  ],
  [
    "consulting",
    "Consulting",
    "side",
    "#2d3440",
    "#769dd3",
    "Strong brand rail and organised totals.",
  ],
  [
    "creative",
    "Creative Studio",
    "side",
    "#3c2941",
    "#d78ab5",
    "Distinctive but client-appropriate.",
  ],
  [
    "construction",
    "Construction",
    "band",
    "#293238",
    "#e0a348",
    "Robust structure for services and materials.",
  ],
  [
    "legal",
    "Legal",
    "formal",
    "#242628",
    "#8d775f",
    "Traditional styling for professional practices.",
  ],
  [
    "medical",
    "Medical",
    "clean",
    "#17423e",
    "#67b9a7",
    "Calm, clear and trustworthy.",
  ],
  [
    "retail",
    "Retail",
    "band",
    "#253a48",
    "#64b9df",
    "Friendly presentation for products and services.",
  ],
  [
    "hospitality",
    "Hospitality",
    "side",
    "#3b3027",
    "#d1a36d",
    "Warm premium treatment for guest services.",
  ],
  [
    "technology",
    "Technology",
    "side",
    "#182b38",
    "#54bceb",
    "Modern modular layout for digital work.",
  ],
  [
    "monochrome",
    "Monochrome",
    "formal",
    "#17191a",
    "#767676",
    "Ink-efficient and dependable in print.",
  ],
  [
    "compact",
    "Compact",
    "clean",
    "#24343b",
    "#7896a2",
    "More line items without visual clutter.",
  ],
  [
    "premium",
    "Premium",
    "formal",
    "#202737",
    "#b39a5c",
    "Elegant detail for premium client work.",
  ],
  [
    "freelancer",
    "Freelancer",
    "band",
    "#26364b",
    "#6eaee1",
    "Approachable and professional for independent work.",
  ],
  [
    "botswana",
    "Botswana Business",
    "band",
    "#17252d",
    "#65b8e7",
    "Clean local-business presentation.",
  ],
  [
    "statement",
    "Statement",
    "side",
    "#25323a",
    "#87a6b5",
    "Detailed, systematic and built for record keeping.",
  ],
];

const mapTemplates = (items, type) =>
  items.map(
    ([id, name, layout, primary, accent, photoOrDescription, description]) => ({
      id: `${type}-${id}`,
      name,
      layout,
      primary,
      accent,
      photo: description ? photoOrDescription : "none",
      description: description || photoOrDescription,
      recommended: ["baakanya-auto", "modern-ats", "corporate"].includes(id),
      type,
    }),
  );

export const cvTemplates = mapTemplates(careerBase, "cv");
export const coverLetterTemplates = mapTemplates(careerBase, "cover");
export const invoiceTemplates = mapTemplates(businessBase, "invoice");
export const quotationTemplates = mapTemplates(businessBase, "quotation");
