create extension if not exists pgcrypto with schema extensions;

alter table public.trial_records
  add column if not exists email_fingerprint_hash text;

create unique index if not exists one_trial_per_user
  on public.trial_records(user_id);
create unique index if not exists one_trial_per_email_fingerprint
  on public.trial_records(email_fingerprint_hash)
  where email_fingerprint_hash is not null;
create unique index if not exists one_trial_per_device_fingerprint
  on public.trial_records(device_fingerprint_hash)
  where device_fingerprint_hash is not null;
create index if not exists trial_records_ip_date_idx
  on public.trial_records(ip_fingerprint_hash, trial_start_date desc);

create table if not exists public.trial_reservations (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  email_normalized text not null,
  email_fingerprint_hash text not null,
  device_fingerprint_hash text not null,
  ip_fingerprint_hash text not null,
  status text not null default 'active'
    check (status in ('active', 'claimed', 'expired', 'blocked')),
  expires_at timestamptz not null,
  claimed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists trial_reservations_email_idx
  on public.trial_reservations(email_fingerprint_hash, created_at desc);
create index if not exists trial_reservations_device_idx
  on public.trial_reservations(device_fingerprint_hash, created_at desc);
create index if not exists trial_reservations_ip_idx
  on public.trial_reservations(ip_fingerprint_hash, created_at desc);

create table if not exists public.abuse_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  email_fingerprint_hash text,
  device_fingerprint_hash text,
  ip_fingerprint_hash text,
  user_agent_hash text,
  allowed boolean not null default false,
  reason text not null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists abuse_events_email_date_idx
  on public.abuse_events(email_fingerprint_hash, created_at desc);
create index if not exists abuse_events_device_date_idx
  on public.abuse_events(device_fingerprint_hash, created_at desc);
create index if not exists abuse_events_ip_date_idx
  on public.abuse_events(ip_fingerprint_hash, created_at desc);

alter table public.trial_reservations enable row level security;
alter table public.abuse_events enable row level security;
revoke all on public.trial_reservations from anon, authenticated;
revoke all on public.abuse_events from anon, authenticated;

-- Users may edit their display details, never their plan or trial dates.
revoke update on public.profiles from authenticated;
grant update(name, phone) on public.profiles to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  insert into profiles(id, name, plan_type)
  values(new.id, new.raw_user_meta_data->>'name', 'none')
  on conflict (id) do nothing;
  insert into credits(user_id, balance) values(new.id, 0)
  on conflict (user_id) do nothing;
  return new;
end
$$;

create or replace function public.handle_email_confirmed()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  reservation public.trial_reservations%rowtype;
  reservation_token text;
  reservation_found boolean := false;
  eligible boolean := false;
  denial_reason text := 'missing_reservation';
begin
  if old.email_confirmed_at is null and new.email_confirmed_at is not null then
    reservation_token := new.raw_user_meta_data->>'trial_reservation_token';
    if coalesce(reservation_token, '') <> '' then
      select * into reservation
      from public.trial_reservations
      where token_hash = encode(extensions.digest(convert_to(reservation_token, 'UTF8'), 'sha256'), 'hex')
        and status = 'active'
        and expires_at > now()
        and claimed_by is null
        and email_normalized = public.normalize_trial_email(new.email)
      for update;
      reservation_found := found;
    end if;

    if reservation_found then
      if exists (
        select 1 from public.trial_records
        where email_normalized = reservation.email_normalized
           or email_fingerprint_hash = reservation.email_fingerprint_hash
           or device_fingerprint_hash = reservation.device_fingerprint_hash
           or user_id = new.id
      ) then
        denial_reason := 'identity_already_used';
      elsif (
        select count(*) from public.trial_records
        where ip_fingerprint_hash = reservation.ip_fingerprint_hash
          and trial_start_date >= now() - interval '90 days'
      ) >= 3 then
        denial_reason := 'ip_trial_limit';
      else
        begin
          insert into public.trial_records(
            user_id,
            email_normalized,
            email_fingerprint_hash,
            device_fingerprint_hash,
            ip_fingerprint_hash,
            trial_start_date,
            trial_end_date
          ) values (
            new.id,
            reservation.email_normalized,
            reservation.email_fingerprint_hash,
            reservation.device_fingerprint_hash,
            reservation.ip_fingerprint_hash,
            now(),
            now() + interval '7 days'
          );
          update public.profiles
          set trial_start_date = now(),
              trial_end_date = now() + interval '7 days',
              plan_type = 'trial'
          where id = new.id;
          update public.trial_reservations
          set status = 'claimed', claimed_by = new.id
          where id = reservation.id;
          eligible := true;
          denial_reason := 'trial_activated';
        exception when unique_violation then
          denial_reason := 'identity_race_blocked';
        end;
      end if;
    elsif coalesce(reservation_token, '') <> '' then
      denial_reason := 'invalid_or_expired_reservation';
    end if;

    if not eligible then
      update public.profiles
      set trial_start_date = null, trial_end_date = null, plan_type = 'none'
      where id = new.id;
      if reservation_found then
        update public.trial_reservations
        set status = 'blocked', claimed_by = new.id
        where id = reservation.id;
      end if;
    end if;

    insert into public.abuse_events(
      event_type,
      email_fingerprint_hash,
      device_fingerprint_hash,
      ip_fingerprint_hash,
      allowed,
      reason,
      user_id
    ) values (
      'trial_activation',
      case when reservation_found then reservation.email_fingerprint_hash end,
      case when reservation_found then reservation.device_fingerprint_hash end,
      case when reservation_found then reservation.ip_fingerprint_hash end,
      eligible,
      denial_reason,
      new.id
    );
  end if;
  return new;
end
$$;

create or replace function public.enforce_payment_submission_limits()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.plan_type = 'credits' and new.amount <> 25)
     or (new.plan_type = 'subscription' and new.amount <> 40) then
    raise exception 'invalid payment amount';
  end if;
  if (select count(*) from public.payment_submissions
      where user_id = new.user_id and status = 'pending') >= 3 then
    raise exception 'too many pending payment submissions';
  end if;
  if exists(select 1 from public.payment_submissions
            where user_id = new.user_id
              and submitted_at > now() - interval '10 minutes') then
    raise exception 'please wait before submitting another payment';
  end if;
  return new;
end
$$;

drop trigger if exists enforce_payment_submission_limits
  on public.payment_submissions;
create trigger enforce_payment_submission_limits
before insert on public.payment_submissions
for each row execute procedure public.enforce_payment_submission_limits();

drop policy if exists "upload own receipt" on storage.objects;
create policy "upload own receipt" on storage.objects
for insert to authenticated
with check (
  bucket_id = 'payment-receipts'
  and (storage.foldername(name))[1] = auth.uid()::text
  and lower(name) ~ '\.(png|jpe?g|webp|pdf)$'
  and coalesce((metadata->>'size')::bigint, 0) between 1 and 5242880
);

-- Old, unused reservations and high-volume event logs are bounded automatically.
create or replace function public.cleanup_trial_security_data()
returns void
language sql
security definer
set search_path = public
as $$
  update trial_reservations
    set status = 'expired'
    where status = 'active' and expires_at < now();
  delete from trial_reservations
    where status in ('expired', 'blocked') and created_at < now() - interval '30 days';
  delete from abuse_events
    where created_at < now() - interval '180 days';
$$;
revoke all on function public.cleanup_trial_security_data() from public, anon, authenticated;

create or replace function public.authorize_generation(tool_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  now_at timestamptz := now();
  access_kind text;
  day_count integer;
  trial_count integer;
  credit_balance integer;
begin
  if uid is null then
    return jsonb_build_object('allowed', false, 'reason', 'Sign in to continue.');
  end if;
  if tool_name is null or tool_name !~ '^[a-z0-9_]{2,40}$' then
    return jsonb_build_object('allowed', false, 'reason', 'Invalid generation request.');
  end if;

  perform pg_advisory_xact_lock(hashtextextended(uid::text, 0));
  select count(*) into day_count from generations
    where user_id = uid and created_at >= now_at - interval '24 hours';

  if exists(select 1 from subscriptions
            where user_id = uid and status = 'active' and end_date > now_at) then
    if day_count >= 100 then
      return jsonb_build_object('allowed', false, 'reason', 'Daily fair-use limit reached. Try again tomorrow.');
    end if;
    access_kind := 'subscription';
  elsif exists(select 1 from profiles
               where id = uid and trial_end_date > now_at and plan_type = 'trial') then
    select count(*) into trial_count from generations
      where user_id = uid and access_type = 'trial';
    if day_count >= 20 or trial_count >= 50 then
      return jsonb_build_object('allowed', false, 'reason', 'Free-trial generation limit reached.');
    end if;
    access_kind := 'trial';
  else
    select balance into credit_balance from credits where user_id = uid for update;
    if coalesce(credit_balance, 0) <= 0 then
      return jsonb_build_object('allowed', false, 'reason', 'No active access or credits remain.');
    end if;
    update credits set balance = balance - 1, last_updated = now_at where user_id = uid;
    access_kind := 'credits';
  end if;

  insert into generations(user_id, tool_used, access_type)
  values(uid, tool_name, access_kind);
  return jsonb_build_object(
    'allowed', true,
    'accessType', access_kind,
    'remainingCredits', case when access_kind = 'credits' then credit_balance - 1 else null end
  );
end
$$;
revoke all on function public.authorize_generation(text) from public, anon;
grant execute on function public.authorize_generation(text) to authenticated;
